config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('booking/', include('booking.urls')),
    path('customer/', include('customer.urls')),
    path('rentel/', include('rentel.urls')),
]

login/urls.py
from django.urls import path

from login import views

app_name = 'login'

urlpatterns = [
    path('user/', views.user_login, name="user-login"),
    path('user1/', views.manager_login, name='manager-login'),
    path('signup/', views.user_signup, name="user-signup"),
    path('signup1/', views.manager_signup, name='manager-signup'),
    path('logout/', views.logout, name='logout'),
]

booking/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Contact(models.Model):
    name = models.CharField(max_length=64, null=True)
    gender = models.CharField(max_length=20)
    profile_pic = models.ImageField(
        upload_to="image",
        height_field=None,
        width_field=None,
        max_length=None,
        blank=True
    )
    phone_number = models.CharField(max_length=50)
    address = models.TextField()
    state = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.gender


class Rental(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    user = models.ManyToManyField(User, through="Booking")
    name_yacht = models.CharField(max_length=100)
    price = models.DecimalField(default=2000.00, max_digits=7, decimal_places=2)
    is_available = models.BooleanField(default=True)
    yacht_image = models.ImageField(
        upload_to="yacht",
        height_field=None,
        width_field=None,
        max_length=None,
        default='0.jpeg'
    )

    def __str__(self):
        return "Renter: " + str(self.name_yacht)


class Booking(models.Model):
    rental = models.ForeignKey(Rental, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_day = models.DateField()
    end_day = models.DateField()
    amount_people = models.PositiveSmallIntegerField()
    booked_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{str(self.start_day)} : {self.end_day}"

templates/manager_dash/add-rental.html
{% extends 'base/base.html'%}
{% block content%}
<div class="row">
    <div class="col l8 offset-l2 m10 offset-m1 s12">
        <div class="card-panel">
            {% if messages %}
            {% for messsage in messages %}
            {% if messsage.tags == 'info' %}
            <div class='chip green white-text'>{{messsage}}</div>
            {% endif %}
            {% if messsage.tags == 'warning' %}
            <div class='chip red white-text'>{{messsage}}</div>
            {% endif %}
            <br>
            {% endfor %}
            {% endif %}
            <div class="row">
                <form class="col s12" method="POST" action="/rentel/next/" enctype="multipart/form-data">{% csrf_token %}
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="first_name">Name Yacht</label>
                            <input placeholder="Enter Rental" id="first_name" type="text" name="rental">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <label>Rental</label>
                            <select class="browser-default" name="rental">
                                <option value="wyspy-kanaryjskie">Wyspy Kanaryjskie</option>
                                <option value="wlochy">Wlochy</option>
                                <option value="karaiby">Karaiby</option>
                                <option value="baleary">Baleary</option>
                                <option value="grecja">Grecja</option>
                                <option value="chorwacja">Chorwacja</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="price">Price</label>
                            <input type="text" name="price" id="price">
                        </div>
                    </div>
                    <div class="row">
                        <div class="file-field input-field col s12">
                            <div class="btn red lighten-2">
                                <span>
                                    <i class="material-icons left black-text text-lighten-1">image</i> Yacht Image</span>
                                    <input type="file" name="yacht_image">
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="no_of_days_advance">No of days in advance</label>
                            <input type="text" name="no_of_days_advance" id="no_of_days_advance">
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="start_day">From when rental yacht will be available for booking</label>
                            <input type="text" name="start_day" id="start_day" class="datepicker">
                        </div>
                    </div>
                    <div class="center">
                        <input type="submit" class="btn green btn-large" value="Add Rental">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $('.datepicker').pickadate({
        selectMonths: true,
        selectYears: 15,
        today: 'Today',
        clear: 'Clear',
        close: 'Ok',
        closeOnSelect: false,
    });

</script>
{% endblock %}

templates/manager_dash/edit-rental.html
{% extends 'base/base.html'%}
{% block content%}
<div class="row">
    <div class="col l8 offset-l2 m10 offset-m1 s12">
        <div class="card-panel">
            <h4>Updating the Data for rental No: {{rental.rental_no}}</h4>
            {% if messages %}
            {% for messsage in messages %}
            {% if messsage.tags == 'info' %}
            <div class='chip green white-text'>{{messsage}}</div>
            {% endif %}
            {% if messsage.tags == 'warning' %}
            <div class='chip red white-text'>{{messsage}}</div>
            {% endif %}
            <br>
            {% endfor %}
            {% endif %}
            <div class="row">
                <form class="col s12" method="POST" action="/rentel/next/">{% csrf_token %}
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="name_yacht">Name Yacht</label>
                            <input type="text" name="name_yacht" id="name_yacht"
                                   value="{{rental.name_yacht}}">
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="price">Price</label>
                            <input type="text" name="price" id="price" value="{{rental.price}}">
                        </div>
                    </div>
                    <div class="center">
                        <input type="submit" class="btn green btn-large" value="Update Rental">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/manager_dash/index.html
{% extends 'base/base.html'%}
{% block content%}
<link href="https://fonts.googleapis.com/css?family=Fredoka+One|Shadows+Into+Light&display=swap" rel="stylesheet">

<div class="row">
    <div class="center" style="margin-top:2%">
        {% if messages %}
        {% for messsage in messages %}
        {% if messsage.tags == 'info' %}
        <div class='chip green white-text'>{{messsage}}</div>
        {% endif %}
        {% if messsage.tags == 'warning' %}
        <div class='chip red white-text'>{{messsage}}</div>
        {% endif %}
        <br>
        {% endfor %}
        {% endif %}
    </div>
    <div class="col offset-l1 l4 offset-m1 m5 s6">
        <div class="card-panel center">
            <h5 style="font-family: 'Shadows Into Light', cursive;" class='blue-text'>Occupied Rental Status</h5>
            <h3 style="font-family: 'Fredoka One', cursive;">
                {{booked}}
            </h3>
        </div>
    </div>
    <div class="col offset-l1 l4 m5 s6">
        <div class="card-panel center">
            <h5 style="font-family: 'Shadows Into Light', cursive;" class='blue-text'>Total Rental to manage</h5>
            <h3 style="font-family: 'Fredoka One', cursive;">
                {{rental_data.count}}
            </h3>
        </div>
    </div>
    <div class="col l8 offset-l2 m10 offset-m1 s12">
        <div class="center">
            <a class="btn green lighten-2" href="/rentel/new/">Add Rental</a>
        </div>
        <h3 style="font-family: 'Fredoka One', cursive;" class="brown-text">Rental Status</h3>
        <div id="message">
        </div>
        {% if data1 %}
        <table class="highlight bordered responsive-table">
            <thead class="red lighten-4">
            <tr>
                <th>Rental</th>
                <th>Price</th>
                <th>Customer Name</th>
                <th>Booked On</th>
                <th>Booking Data</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for rental in data1%}
            <tr>
                <td>{{rental.name_yacht}}</td>
                <td>{{rental.price}}</td>
                {% with data=rental.booking_set.all.0 %}
                <td><a href="/login/user">{{data.user.username}}</a></td>
                <td>{{available_rentals.booked_on}}
                </th>
                <td>
                    {% if rental.is_available%}
                    Available
                    {% else %}
                    {{data.start_day}} to {{data.end_day}}
                    {% endif %}
                </td>
                <td><a class="btn blue" href="/rentel/update/{{rental.id}}">Edit</a></td>
                <td><a class="btn red cancel-btn" href="/booking/delete-yacht/{{rental.id}}" id="{{rental.id}}">Delete</a></td>
                {% endwith %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>Sorry no rental has been added by you, please add a rental now <a href="/login/user/">Here</a></p>
        {% endif %}
    </div>
</div>
<script>
    cancel_btn = document.querySelectorAll(".cancel-btn")
    cancel_btn.forEach((data) => {
        data.addEventListener("click", (e) => {
            e.preventDefault()
            id = e.target.id
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    console.log(xhttp.responseText)
                    document.getElementById("message").innerHTML = "<div class='chip green white-text'>" + xhttp.responseText + "</div>";
                    window.setTimeout(function () {
                        location.reload()
                    }, 1000)
                }
            };
            xhttp.open("GET", "/booking/delete-yacht/" + id, true);
            xhttp.send();
        })
    })
</script>
{% endblock %}